# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hasil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skor', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('nomor_induk', models.IntegerField(default=0)),
                ('tanggal_reg', models.DateTimeField(verbose_name='tanggal registrasi')),
            ],
        ),
        migrations.CreateModel(
            name='Soal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soal', models.TextField()),
                ('jawaban', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='hasil',
            name='siswa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answerchecker.Siswa'),
        ),
        migrations.AddField(
            model_name='hasil',
            name='soal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answerchecker.Soal'),
        ),
    ]
