# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answerchecker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='nomor_induk',
            field=models.CharField(max_length=20),
        ),
    ]
