# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answerchecker', '0002_auto_20160121_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasil',
            name='jawaban',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
